import { PixelWeaponIcon } from "@/components/pixel-weapon-icon";

export type Weapon = (typeof weaponList)[0];

export const weaponList = [
  {
    icon: <PixelWeaponIcon type="sword" />,
    name: "React",
    speed: 90,
    proficiency: 75,
    knowledge: 75,
    experience: "4 years",
  },
  {
    icon: <PixelWeaponIcon type="bow" />,
    name: "Tailwind",
    speed: 90,
    proficiency: 70,
    knowledge: 75,
    experience: "4 years",
  },
  {
    icon: <PixelWeaponIcon type="hammer" />,
    name: "JS/TS",
    speed: 75,
    proficiency: 70,
    knowledge: 70,
    experience: "4 years",
  },
  {
    icon: <PixelWeaponIcon type="shield" />,
    name: "Next.js",
    speed: 70,
    proficiency: 60,
    knowledge: 60,
    experience: "4 years",
  },
  {
    icon: <PixelWeaponIcon type="wand" />,
    name: "emotion",
    speed: 70,
    proficiency: 60,
    knowledge: 55,
    experience: "3 years",
  },
  {
    icon: <PixelWeaponIcon type="axe" />,
    name: "SWR",
    speed: 60,
    proficiency: 60,
    knowledge: 65,
    experience: "2 years",
  },
  {
    icon: <PixelWeaponIcon type="staff" />,
    name: "Recoil",
    speed: 65,
    proficiency: 50,
    knowledge: 50,
    experience: "2 years",
  },
  {
    icon: <PixelWeaponIcon type="dagger" />,
    name: "Redux",
    speed: 50,
    proficiency: 50,
    knowledge: 50,
    experience: "3 years",
  },
  {
    icon: <PixelWeaponIcon type="bow" />,
    name: "NestJS",
    speed: 40,
    proficiency: 30,
    knowledge: 25,
    experience: "2 years",
  },
  {
    icon: <PixelWeaponIcon type="dagger" />,
    name: "Vue.js",
    speed: 30,
    proficiency: 15,
    knowledge: 15,
    experience: "3 months",
  },
];
